### ISSUE TITLE
FR: Ignore rules 

### ISSUE THREAD

**Issue by sliedig** [awslabs/serverless-rules#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In certain circumstances I may want to ignore rules. Would like to be able to configure which rules I don't want to check and see warnings for. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nmoutschen** [comment]
Hey @sliedig !

Thanks a lot for your feedback.

This is already supported out of the box for both [`cfn-lint`](https://github.com/aws-cloudformation/cfn-lint#configuration) and [`tflint`](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md), but I think it would be good to have examples on the documentation on how to do this.

**Comment by nmoutschen** [comment]
I've added a section in the documentation on how to ignore rules. This will be available with the next release.
