### ISSUE TITLE
Potential issue running with Python 3.9

### ISSUE THREAD

**Issue by danballance** [awslabs/serverless-rules#94]
So we are trying to lint with a python 3.9 lambda runtime. We want to pick up version `0.54` of `cfn-lint` which now includes support for python 3.9 (https://github.com/aws-cloudformation/cfn-lint/issues/2102). However when we install this project's rules with the latest published package on pypi (July `v0.2.1`), the `cfn-lint` version is pinned to `cfn-lint = ">=0.49.2,<0.53.0"` and `cfn-lint` is downgraded to `0.52.0`.

When I check the current file, I can see the `cfn-lint` version has been bumped in main:
https://github.com/awslabs/serverless-rules/blob/d2b4763122c419812a001f4cfbc09a505591ddda/cfn-lint-serverless/pyproject.toml#L11

So perhaps I just need to wait for a next release? If so, any idea when that might be?

Thanks in advance,

Dan.

**Comment by nmoutschen** [comment]
Hey @danballance !

Thanks a lot for creating this issue. I've just released a new minor version with the bumps in dependencies: https://github.com/awslabs/serverless-rules/releases/tag/v0.2.2

Let me know if it works for you! 😄

**Comment by nmoutschen** [comment]
Closing this issue for now but feel free to reopen if you have any issue.
